export const BASE_URL = '/'
export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const SCOREBOARD_ROUTE = '/scoreboard'
export const TASKS_ROUTE = '/'